# -*- coding: utf-8 -*-
"""Mattespilt_take_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qJMRIT8wXxDErHuCdYpwD5I2MdHgpi6h
"""

from time import sleep
from random import randint
    
fortsette = "ja"
liv = 3
print("Du har", liv ,"liv")
top = 5
rs = 0


while fortsette == "ja":
    svar = 100000
    t1 = randint(0,top)
    t2 = randint(0,top)
    
    while not svar == t1*t2:
        print("Hva blir ", t1, "*", t2, "? ",sep="",end=" ")
        svar = int(input())

        if svar == t1*t2:
            print()
            print("Korrekt!")
            rs = rs+1
            if rs == top: 
                top = top + 5
                print("Du har nådd lv", rs/5)
            fortsette = str(input("Ønsker du å fortsette? "))
            fortsette = fortsette.lower()
            if not fortsette == "ja":
                print()
                print("Bra spilt")
                break
        else:
            liv = liv-1
            print("Feil, du har", liv ,"liv igjen")

            if liv == 0:
                svar = t1*t2
                print()
                print("Du døde."); sleep(1.5)
                print("Svaret var", svar); sleep(1)
#                 fortsette = str(input("Ønsker du å fortsette? "))    #Dette e hardmode
#                 fortsette = fortsette.lower()
#                 if not fortsette == "ja":
#                 sleep(1)
                print()
                print("GAME ",end=""); sleep(1.5); print("OVER")
                break
print()
sleep(1)
print("Du nådde lv", rs//5); sleep(1)
print("Din score: ",end=""); sleep(1)
print(rs)